install:
	composer install
	npm install

test:
	php artisan test

analyse:
	vendor/bin/phpstan analyse

build:
	npm run build
	docker compose build

up:
	docker compose up -d

down:
	docker compose down
